

const ToolType = [
    { label: "Select an ToolType", value: "" },
    { label: "Drill", value: "Drill" },
    { label: "Saw", value: "Saw" },
    { label: "jigsaw", value: "jigsaw" },
    { label: "Circular saw", value: "Circular saw" },
    { label: "Reciprocating saw", value: "Reciprocating saw" },
    { label: "Chainsaw", value: "Chainsaw" },
    { label: "Angle grinder", value: "Angle grinder"},
    { label: "Impact driver", value: "Impact driver" },
    { label: "Impact wrench", value: "Impact wrench" },
    { label: "Rotary hammer", value: "Rotary hammer" },
    { label: "Demolition hammer", value: "Demolition hammer" },
    { label: "Multi-tool", value: "Multi-tool" },
    { label: "Belt sander", value: "Belt sander" },
    { label: "Orbital sander", value: "Orbital sander" },
    { label: "Sheet sander", value: "Sheet sander" },
    { label: "Bench grinder", value: "Bench grinder" },
    { label: "Grinder", value: "Grinder" },
    { label: "Sander", value: "Sander" },
    { label: "Planer", value: "Planer" },
    { label: "Router", value: "Router" },
    { label: "Heat gun", value: "Heat gun" },
    { label: "Nailer", value: "Nailer" },
    { label: "Air compressor", value: "Air compressor" },
    { label: "Welder", value: "Welder" },
    { label: "Generator", value: "Generator" },
    { label: "Pressure washer", value: "Pressure washer" },
    { label: "Vacuum", value: "Vacuum" },
    { label: "Other", value: "Other" },
]

export default ToolType;